#joomla版本，需定期维护
joomla_version: v3.8.1

#Web服务器：apache | nginx，通过交互式选择获取
joomla_webs: apache

joomla_vhost_dir: /etc/httpd/vhost
joomla_vhost_src: vhost.conf
joomla_service: httpd
joomla_owner: apache
