#Web服务器：apache | nginx，通过交互式选择获取
joomla_webs: apache

joomla_vhost_dir: /etc/httpd/vhost
joomla_vhost_src: vhost.conf
joomla_service: httpd
joomla_owner: apache
joomla_name: "joomla"
joomla_title: "Joomla"
joomla_download_url: "https://github.com/joomla/joomla-cms"
joomla_version: "13.1"  #版本号需定期维护
