---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    joomla_vhost_dir: "{{php_runtime_meta[ansible_distribution][joomla_webs].vhost_dir}}"
    joomla_vhost_src: "{{php_runtime_meta[ansible_distribution][joomla_webs].vhost_src}}"
    joomla_service: "{{php_runtime_meta[ansible_distribution][joomla_webs].service}}"
    joomla_owner: "{{php_runtime_meta[ansible_distribution][joomla_webs].owner}}"

- debug:
    msg: runtime {{ joomla_vhost_dir }}, {{joomla_vhost_src}}, {{joomla_service}}, {{joomla_owner}}, {{joomla_webs}}, {{ansible_distribution}}

# Joomla  
- name: Remove extra dir
  shell: |
    rm -rf /data/wwwroot/www.example.com
    rm -rf /data/wwwroot/{{joomla_name}}

- name: Create Joomla folder
  file:
    path: /data/wwwroot/{{joomla_name}}
    state: directory
    mode: 0750

- name: Download joomla
  git:
    repo: "{{joomla_download_url}}"
    dest: /data/wwwroot/joomla
    version: "{{joomla_version}}"

- name: Copy PHP Config file
  copy: src=php.ini dest=/etc/php.ini

# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{joomla_owner}}:{{joomla_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    copy: src={{joomla_vhost_src}} dest={{joomla_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{joomla_service}} state=restarted enabled=yes